name: efm

services:
  db:
    container_name: db
    image: postgres:17.2-alpine3.21
    expose:
      - 5432
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: passwd
    restart: always
    shm_size: 128mb
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 15s
      retries: 3
    networks:
      - efm_db
    volumes:
      - efm_db:/var/lib/postgresql/data

networks:
  efm_db:
    name: efm_db

volumes:
  efm_db:
    name: efm_db
